### ISSUE TITLE
Upgrade test matrix

### ISSUE THREAD

**Issue by ubmarco** [useblocks/sphinx-test-reports#108]
Current state:

Dependencies
```
[project]
requires-python = ">=3.6"

dependencies = [
  "sphinx>4.0",
  "sphinx-needs>=1.0.1"  
]
```
Tested against the combinations of:
```
PYTHON_VERSIONS = ["3.10", "3.12"]
SPHINX_VERSIONS = ["5.0", "7.2.5", "8.1.3"]
SPHINX_NEEDS_VERSIONS = ["2.1", "4.2"]
```

Sphinx-Needs latest version is 5.1. Its dependencies are
```
requires-python = ">=3.9,<4"
dependencies = [
  "sphinx>=7.0,<9",
]
```
Tested against
```
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.12"]
        sphinx-version: ["7.0", "8.0"]
        include:
          - os: "ubuntu-latest"
            python-version: "3.9"
            sphinx-version: "7.0"
          - os: "windows-latest"
            python-version: "3.9"
            sphinx-version: "7.0"
          - os: "windows-latest"
            python-version: "3.12"
            sphinx-version: "8.0"
```

sphinx-test-reports
1. should support the most recent Sphinx-Needs version
2. should support the last 3 major Sphinx-Needs version (currently 3.0.0, 4.2.0, 5.1.0).
3. may support older Sphinx-Needs versions.
4. should support and test against the same Python & Sphinx versions as Sphinx-Needs.
5. should not supported unmaintained Python versions.
6. should test on Windows

If there is good reason not to support any of the older Sphinx-Needs versions and deviate from point 2., it should be documented.
